(* WARNING: This file is generated by Edsger, the DeepSEA compiler.
            All modification will be lost when regenerating. *)
(* Module ERC20WrappedEth.DataTypes for ERC20WrappedEth.ds *)
Require Import BinPos.
Require Import DeepSpec.Runtime.
Require Import ERC20WrappedEth.EdsgerIdents.

Section EdsgerGen.


Definition HASH_address_Z32 := (Int256Tree.t Z32).

Definition HASH_address_HASH_address_Z32 := (Int256Tree.t (Int256Tree.t Z32)).

End EdsgerGen.
