(* WARNING: This file is generated by Edsger, the DeepSEA compiler.
            All modification will be lost when regenerating. *)
(* Module ERC20WrappedEth.EdsgerIdents for ERC20WrappedEth.ds *)
Require Import BinPos.  (* positive_scope *)
Require Import backend.AST. (* for ident *)

Definition ident_ERC20WrappedEth_allowance : ident  := 550%positive.
Definition ident_ERC20WrappedEth_approve : ident  := 551%positive.
Definition ident_ERC20WrappedEth_approveSafely : ident  := 552%positive.
Definition ident_ERC20WrappedEth_balanceOf : ident  := 553%positive.
Definition ident_ERC20WrappedEth_burn : ident  := 554%positive.
Definition ident_ERC20WrappedEth_constructor : ident  := 555%positive.
Definition ident_ERC20WrappedEth_mint : ident  := 556%positive.
Definition ident_ERC20WrappedEth_totalSupply : ident  := 557%positive.
Definition ident_ERC20WrappedEth_transfer : ident  := 558%positive.
Definition ident_ERC20WrappedEth_transferFrom : ident  := 559%positive.
Definition var_ERC20WrappedEth_ERC20WrappedEth__totalSupply_ident : ident  := 560%positive.
Definition var_ERC20WrappedEth_ERC20WrappedEth_allowances_ident : ident  := 561%positive.
Definition var_ERC20WrappedEth_ERC20WrappedEth_wrapped_ident : ident  := 562%positive.
