(* WARNING: This file is generated by Edsger, the DeepSEA compiler.
            All modification will be lost when regenerating. *)
(* Module trivial.DataTypes for trivial.ds *)
Require Import BinPos.
Require Import DeepSpec.Runtime.
Require Import trivial.EdsgerIdents.

Section EdsgerGen.


End EdsgerGen.
