(* WARNING: This file is generated by Edsger, the DeepSEA compiler.
            All modification will be lost when regenerating. *)
(* Module trivial.DataTypeOps for trivial.ds *)
Require Import BinPos.
Require Import DeepSpec.Runtime.
Require Import trivial.EdsgerIdents.
Require Import trivial.DataTypes.

Section EdsgerGen.

Require Import backend.MachineModel.
Program Definition ext_call_me {adata: Type} (me : machine_env adata) (ext_contract : int256) := {|
  me_address := ext_contract;
  me_origin := me_origin me;
  me_caller := me_address me;
  me_callvalue := me_callvalue me; (* FIXME: the callvalue modeling is wrong *)
  me_coinbase := me_coinbase me;
  me_timestamp := me_timestamp me;
  me_number := me_number me;
  me_chainid := me_chainid me;
  me_balance := me_balance me;
  me_blockhash := me_blockhash me;
  me_transfer := me_transfer me;
  me_callmethod := me_callmethod me;
  me_log := me_log me;
|}.
Next Obligation.
destruct me; simpl. destruct me_valid as [[]]. auto.
Defined.
Record global_abstract_data_type : Type := {
  Outgoing_transfer_recipient_and_amount : option (int256 * Z);
  Trivial_seenTrueYet : bool
}.


Definition update_Outgoing_transfer_recipient_and_amount new_outgoing_transfer_recipient_and_amount (glabs_a : global_abstract_data_type)
  := Build_global_abstract_data_type new_outgoing_transfer_recipient_and_amount (Trivial_seenTrueYet glabs_a) .
Definition update_Trivial_seenTrueYet glabs_b (glabs_a : global_abstract_data_type)
  := Build_global_abstract_data_type  (Outgoing_transfer_recipient_and_amount glabs_a) glabs_b .

Definition init_global_abstract_data : global_abstract_data_type := {|
  Outgoing_transfer_recipient_and_amount := None;
  Trivial_seenTrueYet := false
|}.

Definition block := positive.
Definition global_low_level_invariant (n : block)(abd : global_abstract_data_type) := True.
End EdsgerGen.

Lemma Trivial_seenTrueYet_of_update_Trivial_seenTrueYet : forall _x (glabs_a : global_abstract_data_type),
  Trivial_seenTrueYet (update_Trivial_seenTrueYet _x glabs_a) = _x.
Proof. intros. destruct glabs_a. reflexivity. Qed.
Hint Rewrite Trivial_seenTrueYet_of_update_Trivial_seenTrueYet : updates.

Opaque Trivial_seenTrueYet update_Trivial_seenTrueYet.
