(* WARNING: This file is generated by Edsger, the DeepSEA compiler.
            All modification will be lost when regenerating. *)
(* Module trivial.EdsgerIdents for trivial.ds *)
Require Import BinPos.  (* positive_scope *)
Require Import backend.AST. (* for ident *)

Definition ident_Trivial_boolToInt : ident  := 550%positive.
Definition ident_Trivial_boolToIntTracker : ident  := 551%positive.
Definition ident_Trivial_constructor : ident  := 552%positive.
Definition var_Trivial_Trivial_seenTrueYet_ident : ident  := 553%positive.
