(* WARNING: This file is generated by Edsger, the DeepSEA compiler.
            All modification will be lost when regenerating. *)
(* Module Crowdfunding.DataTypes for Crowdfunding.ds *)
Require Import BinPos.
Require Import DeepSpec.Runtime.
Require Import Crowdfunding.EdsgerIdents.

Section EdsgerGen.


Definition message := Z32.

Definition HASH_address_Z32 := (Int256Tree.t Z32).

End EdsgerGen.
