(* WARNING: This file is generated by Edsger, the DeepSEA compiler.
            All modification will be lost when regenerating. *)
(* Module Crowdfunding.EdsgerIdents for Crowdfunding.ds *)
Require Import BinPos.  (* positive_scope *)
Require Import backend.AST. (* for ident *)

Definition ident_Crowdfunding_claim : ident  := 550%positive.
Definition ident_Crowdfunding_constructor : ident  := 551%positive.
Definition ident_Crowdfunding_donate : ident  := 552%positive.
Definition ident_Crowdfunding_getFunds : ident  := 553%positive.
Definition var_Crowdfunding_Crowdfunding_backers_ident : ident  := 554%positive.
Definition var_Crowdfunding_Crowdfunding_funded_ident : ident  := 555%positive.
Definition var_Crowdfunding_Crowdfunding_goal_ident : ident  := 556%positive.
Definition var_Crowdfunding_Crowdfunding_max_block_ident : ident  := 557%positive.
Definition var_Crowdfunding_Crowdfunding_owner_ident : ident  := 558%positive.
